# Arewa Data Science Academy
## Deep Learning Cohort2.0
**Name: Abdulazeez Ahmad**

**Email: azeezahmad518@gmail.com**

**Title: Week 1 Solution**



**Exercises Solution**

In [13]:
# Exercise 1
# No code solution

In [14]:
# Exercise 2
# import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

In [24]:
# Exercise 3

# Creating another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform Matrix Multiplication
mat_mult = torch.mm(random_tensor, random_tensor_2.T)
mat_mult

tensor([[2.0054],
        [1.7664],
        [2.1521],
        [1.9626],
        [1.8203],
        [1.6768],
        [2.0795]])

In [16]:
# Exercise 4

# Setting the seed
torch.manual_seed(0)

# Creating a random tensor of shape (7, 7)
random_tensor_3 = torch.rand(7, 7)

# Creating a random tensor of shape (1, 7)
random_tensor_4 = torch.rand(1, 7)

# Matrix Multiplication
mat_mult_2 = torch.matmul(random_tensor_3, random_tensor_4.T)
mat_mult_2


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [17]:
# Exercise 5
# Setting random seed on GPU
torch.cuda.manual_seed(1234)

In [18]:
# Exercise 6

# Set random seed
torch.manual_seed(1234)

#  Check for access to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

# Create two random tensors on GPU
tensor_1 = torch.rand(2, 3).to(device)
tensor_2 = torch.rand(2, 3).to(device)

print((tensor_1, tensor_2))


Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0'))


In [19]:
# Exercise 7

# Perform matrix multiplication on tensor_1 and tensor_2
tensemult = torch.matmul(tensor_1, tensor_2.T)
tensemult, tensemult.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [20]:
# Exercise 8

# Find max
print(f"Maximum value: {tensemult.max()}")

# Find min
print(f"Minimum value: {tensemult.min()}")


Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


In [21]:
# Exercise 9

# Find arg max
print(f"Index where max value occurs: {tensemult.argmax()}")

# Find arg min
print(f"Index where min value occurs: {tensemult.argmin()}")

Index where max value occurs: 3
Index where min value occurs: 0


In [22]:
# Exercise 10

# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_3 = torch.rand(1, 1, 1, 10)

# Remove single dimension
tensor_4 = tensor_3.squeeze()

# Print out tensors and their shapes
print(tensor_3, tensor_3.shape)
print(tensor_4, tensor_4.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
